from .user_update import *
from .user_create import *
from .user_read import *
from .user_address import *
from .user_emotion import *
from .user_deepfakes import *
from .user_note import *
from .doctor_update import *
from .doctor_create import *
from .doctor_read import *
from .music_update import *
from .music_create import *
from .music_read import *
